baseURL = 'https://thorben.online'
languageCode = 'en-us'
title = 'Thorben Online'
theme = 'hugo-theme-hello-friend'

paginate = 5 # number of posts per page

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showReadingTime = false
  # toc = true

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

[languages]
  [languages.en]
    title = "Thorben Online"
    # subtitle = "todo"
    keywords = ""
    copyright = "All content&nbsp; <a href='https://creativecommons.org/licenses/by-sa/4.0/' target = '_blank' >CC-BY-SA</a> Theme & License:&nbsp; <a href='https://github.com/panr/hugo-theme-hello-friend/blob/master/LICENSE.md' target = '_blank' >hello-friend</a>"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      # logoText = "Thorben Online"
      path = "/images/Filled-Logo-Colors.svg"
      alt = "Thorben Online"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      # [[languages.en.menu.main]]
      #   identifier = "showcase"
      #   name = "Showcase"
      #   url = "/showcase"